name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Buildear imagen de Docker y publicar en GHCR
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        image_tag: latest
    - name: Limpiar imagenes de Docker sin taggear
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        delete-untagged: true
